# Generated by Django 5.2.4 on 2025-07-27 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteId', models.AutoField(primary_key=True, serialize=False)),
                ('clienteNombre', models.CharField(max_length=100)),
                ('clienteTelefono', models.CharField(max_length=15)),
                ('clienteEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('clienteDireccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['clienteNombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoOrden',
            fields=[
                ('estadoId', models.AutoField(primary_key=True, serialize=False)),
                ('estadoNombre', models.CharField(max_length=50)),
                ('estadoDescripcion', models.TextField(blank=True, null=True)),
                ('estadoColor', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name': 'Estado de Orden',
                'verbose_name_plural': 'Estados de Órdenes',
                'db_table': 'estado_orden',
                'ordering': ['estadoNombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('odtId', models.AutoField(primary_key=True, serialize=False)),
                ('odtNumero', models.CharField(max_length=20, unique=True)),
                ('odtFecha', models.DateTimeField(auto_now_add=True)),
                ('odtDescripcion', models.TextField()),
                ('odtEstado', models.CharField(default='Pendiente', max_length=20)),
                ('odtModelo', models.CharField(max_length=50)),
                ('odtMarca', models.CharField(max_length=50)),
                ('odtFalla', models.TextField(blank=True, null=True)),
                ('odtFechaEntrega', models.DateTimeField(blank=True, null=True)),
                ('asignadoA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionordenes.cliente')),
                ('creadoPor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estadoOrden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionordenes.estadoorden')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'db_table': 'orden_trabajo',
                'ordering': ['-odtFecha'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pagoId', models.AutoField(primary_key=True, serialize=False)),
                ('pagoFecha', models.DateTimeField(auto_now_add=True)),
                ('pagoMonto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagoMetodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de débito'), ('credito', 'Tarjeta de crédito'), ('transferencia', 'Transferencia')], max_length=20)),
                ('ordenTrabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestionordenes.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-pagoFecha'],
            },
        ),
    ]
