# Generated by Django 5.2.4 on 2025-07-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtTipoMaquina',
            field=models.CharField(choices=[('impresora', 'Impresora'), ('plotter', 'Plotter'), ('otro', 'Otro')], default='impresora', max_length=50),
        ),
    ]
