# Generated by Django 5.2.4 on 2025-07-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionordenes', '0002_ordentrabajo_odttipomaquina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='asignadoA',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='creadoPor',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='estadoOrden',
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='odtDescripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='odtEstado',
            field=models.CharField(default='Pendiente', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='odtFecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='odtMarca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='odtModelo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
