# Generated by Django 5.2.4 on 2025-08-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionordenes', '0003_remove_ordentrabajo_asignadoa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('tecnicoId', models.AutoField(primary_key=True, serialize=False)),
                ('tecnicoNombre', models.CharField(max_length=100)),
                ('tecnicoTelefono', models.CharField(max_length=15)),
                ('tecnicoEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'tecnico',
                'ordering': ['tecnicoNombre'],
            },
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='odtFechaEntrega',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtClientAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtClientEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtClientName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtClientPhone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtDiagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtPaymentForm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estadoorden',
            name='estadoColor',
            field=models.CharField(choices=[('#FF0000', 'Sin reparación'), ('#00FF00', 'Lista'), ('#0000FF', 'Diagnosticada'), ('#FFA500', 'No repara'), ('#FFFF00', 'En reparación')], default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='odtTipoMaquina',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
