# Generated by Django 5.2.4 on 2025-08-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionordenes', '0004_tecnico_remove_ordentrabajo_odtfechaentrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='odtNumero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
