# Generated by Django 5.2.4 on 2025-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionordenes', '0005_alter_ordentrabajo_odtnumero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='odtDescripcion',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='odtRecepcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
