# Generated by Django 5.2.5 on 2025-08-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionordenes', '0006_remove_ordentrabajo_odtdescripcion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tecnico',
            new_name='Tecnicos',
        ),
        migrations.DeleteModel(
            name='EstadoOrden',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
